### PR TITLE
Add flake.nix

### PR DESCRIPTION
**Pull request by 3Rafal**

### CODE REVIEW

**Comment by pitag-ha** [comment]
This went through yesterday during my day off, so let me ask about it even though it's already merged: What do you use the Nix flake for? Do you use Nix instead of Opam or do you use both?

**Comment by 3Rafal** [comment]
This is only for nix users, so it doesn't have an impact on "main" workflow.

**Comment by pitag-ha** [comment]
Yes. I was asking because I'm surprised to see it committed. It's the first time I see a Nix flake committed, even though I've worked with Nix users on other projects. It sounds good to me to commit it. I'm just curious.

Do you create a Nix flake for every project you work on? Would you like to upstream a Nix flake to every project you work on?

**Comment by 3Rafal** [comment]
I don't use nix for every project, but fortunately most projects that I work on already have nix setup. 
e.g. whole ocaml editors stack:
https://github.com/ocaml/merlin/blob/master/flake.nix
https://github.com/ocaml/ocaml-lsp/blob/master/flake.nix
https://github.com/ocamllabs/vscode-ocaml-platform/blob/master/flake.nix

**Comment by pitag-ha** [comment]
I should pay more attention to things. Thanks!

**Pull request merged**
