### PR TITLE
Strip location in response for Exception class

### PR DESCRIPTION
**Pull request by xvw**
I'm having trouble understanding how to generate a test that produces an exception. Is it possible to test it on the Merlin branch via Fuzzy-CI?

### CODE REVIEW

**Comment by pitag-ha** [comment]
> Is it possible to test it on the Merlin branch via Fuzzy-CI?

That's probably the easiest solution to test this, yes. If you want to do that before merging this, you can do it on your merlin fork. You'll need to go into the Fuzzy-CI workflow file in merlin, adjust `merl-an`'s repo and commit sha in there to point to your change, and open a PR on your merlin fork itself. That should (hopefully) trigger the Fuzzi-CI and you should be able to see the impact of this change on the Fuzzy-CI output. As a side-effect, that'll also be a good way to test if the CI runs on a fork or not.

**Review by pitag-ha — APPROVED** [review]
Thanks, looks good for me to be merged! Could you open the PR on merlin to pin the Fuzzy CI to the new commit of merl-an? The way I'm expecting that to work is:
- You open a PR to merlin with the new merl-an pin in the Fuzzy CI.
- The Fuzzy CI will fail on that PR as there'll be a diff in the responses it generates.
- You'll quickly skim through the diff checking that the only change in the diff is what you're expecting: the backtraces of exceptions.
- You approve the diff by setting the `fuzzy-diff-looks-good` flag on the PR.
- The Fuzzy CI will run again and pass this time.
- Someone can approve and you can merge the PR.

PD: The two commits in this PR aren't separated coherently: The first commit adds the test, but without adding the test merlin mock, so the first commit alone would fail the test.

**Comment by xvw** [comment]
> You open a PR to merlin with the new merl-an pin in the Fuzzy CI.

Using my own (merl-an) fork? Or using my merl-an fork commit on my merlin's fork?

**Comment by pitag-ha** [comment]
I don't understand (I'm sorry!). I meant to pin to the commit that the default branch of this fork points to now after merging. For that, you need to open a PR on Merlin that updates the commit in line https://github.com/ocaml/merlin/blob/master/.github/workflows/fuzzy-ci.yml#L44 to `6411f0d3847e8b7e66362bcb1f9345a5d3e851ca`. If you prefer that I open and discuss the PR on Merlin, let me know!

**Pull request merged**
